name: Update Last Updated Date

on:
  push:
    branches:
      - main

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Update Last Updated Date
        run: echo "LAST_UPDATED=$(date -u '+%Y-%m-%d')" >> $GITHUB_ENV
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update last updated date"
          add: '.github/workflows/update_date.yml'
